# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: unit tests
        run: swift test -v --parallel --filter XnLevenshteinTests
      - name: coverage
        uses: sersoft-gmbh/swift-coverage-action@v4.0
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
          

  performance-tests:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - name: Run performance tests
        run: swift test -v --filter XnLevenshteinPerformance -Xswiftc -O
      - name: coverage
        uses: sersoft-gmbh/swift-coverage-action@v4.0
      - name: codecov
        run: bash <(curl -s https://codecov.io/bash)
